import Navbar from "./components/Navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "FAJNE CHATKI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
